name: GitHub Actions CI
on:
  pull_request:
    paths:
      - "actions/**"
      - ".github/workflows/actions-ci.yml"

concurrency:
  group: actions-ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: actions

jobs:
  test:
    name: Check
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "16"
          cache: "pnpm"
          cache-dependency-path: actions/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
      - run: make test
      - run: make lint
      - run: make build

      - name: Check if built version was committed
        run: |
          git diff --exit-code || (echo "::error::You forgot to commit the built actions, run 'make' locally" && exit 1)
